//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsesoriasUABC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnosTb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlumnosTb()
        {
            this.Alumnos_Grupos = new HashSet<Alumnos_Grupos>();
        }
    
        public int id_Alumno { get; set; }
        public int matricula { get; set; }
        public string nombre { get; set; }
        public string apellidoP { get; set; }
        public string sexo { get; set; }
        public string apellidoM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumnos_Grupos> Alumnos_Grupos { get; set; }
    }
}
