//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsesoriasUABC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsesoriasTb
    {
        public int Id_asesoria { get; set; }
        public Nullable<int> matricula { get; set; }
        public Nullable<int> id_materia { get; set; }
        public Nullable<int> id_asesor { get; set; }
        public string cvc { get; set; }
        public string time { get; set; }
    }
}
