//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsesoriasUABC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsesoresTb
    {
        public int Id_Asesores { get; set; }
        public string nombre { get; set; }
        public string ApellidoP { get; set; }
        public int codigo_empleado { get; set; }
        public string correo { get; set; }
        public string contraseña { get; set; }
        public string sexo { get; set; }
        public string ApellidoM { get; set; }
    }
}
