//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsesoriasUABC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos
    {
        public int IdEquipo { get; set; }
        public int Folio { get; set; }
        public int Garantia { get; set; }
        public string Equipo { get; set; }
        public string Estado { get; set; }
        public int Presupuesto { get; set; }
        public string Diagnostico { get; set; }
        public string Contacto { get; set; }
        public string Tecnico { get; set; }
        public string FechaIn { get; set; }
        public string FechaOut { get; set; }
        public string TipoEquipo { get; set; }
        public string Ubicacion { get; set; }
    }
}
