//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsesoriasUABC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MateriasTb
    {
        public int id_materia { get; set; }
        public string nombre { get; set; }
        public int clave_materia { get; set; }
        public int plan_estudios { get; set; }
    }
}
