//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsesoriasUABC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temasTb
    {
        public int id_Temas { get; set; }
        public int numero_tema { get; set; }
        public string nombre_tema { get; set; }
        public Nullable<int> id_Materias { get; set; }
    
        public virtual MateriasTb MateriasTb { get; set; }
    }
}
